title: PixelCave
width: 360
scale: 3
levels:
  - pixelcave
templates:
  KNIGHT:
    approximate-width: 40
    approximate-height: 40
    themes:
      - black
      - blue
      - elder
      - gold
      - grey
      - holy
      - red
      - white
      - yellow
      - young
    animation-templates:
      IDLE:
        x: 0
        y: 0
        frames: 4
      RUN:
        x: 8
        y: 0
        frames: 10
      JUMP:
        x: 10
        y: 0
        frames: 7
      FALL:
        x: 10
        y: 6
        frames: 1
      LAND:
        x: 10
        y: 7
        frames: 3
  NAGA:
    approximate-width: 60
    approximate-height: 60
    themes:
      - black
      - blue
      - magma
      - purple
      - red
      - violet
      - void
      - white
    animation-templates:
      IDLE:
        frames: 6
        x: 0
        y: 0